### PR TITLE
Use and anchor mkdirp >=1.0.0

### PR DESCRIPTION
**Pull request by longhotsummer**
Simpler fix for https://github.com/jcoglan/canopy/pull/37

### CODE REVIEW

**Comment by longhotsummer** [comment]
@jcoglan any chance of this getting merged?

**Comment by longhotsummer** [comment]
@jcoglan seeing that people are encountering this problem, would it make sense to merge this to master?

**Comment by jcoglan** [comment]
Hi folks, sorry for the delay here but I finally have some time to catch on maintenance on this project. This change is now in `master` and I'm working towards a v0.4.0 release.

**Comment by jcoglan** [comment]
This should now be fixed as part of the v0.4 release; see https://blog.jcoglan.com/2022/04/01/announcing-canopy-0-4/

**Pull request closed without merging**
