### PR TITLE
Add support for specifying output location

### PR DESCRIPTION
**Pull request by atownley**
I have a project where I want to split the grammar and the output files to better manage multiple language implementations.  Currently, canopy doesn't support this option.  I added it.

Hopefully, this change or something like it will make it in a future release.  It really makes a difference in structuring your projects.

Feel free to ignore the builder bogus checkin.  That was a mistake.

### CODE REVIEW

**Comment by jcoglan** [comment]
Hi @atownley, this is a good idea. The only problem with the implementation is that it doesn't handle languages for which the compiler emits multiple files. For example, try running it with `--lang java` to see what I mean: only a single file is written, and it contains the contents of the last file the compiler emits, so all other compiler output is lost.

For multi-file outputs, we generate a directory named after the grammar; maybe `--out` should override that rather than supplying a literal filename. I'm not sure whether this could live in the `bin` script or whether the path would need to be passed into the builder/compiler, I'll leave that for you to decide.

**Comment by jcoglan** [comment]
Something else occurs to me, prompted by Java but it will affect other language backends we could implement. For JS, Python and Ruby this currently isn't a problem since we emit a single file with no dependencies, but for Java we emit multiple files. In general, multi-file exports will need to import each other, and they might not be able to do this in a strictly relative sense.

For example, if you run `./bin/canopy lib/meta_grammar.peg --lang java` in this repo, the resulting files begin with `package lib.meta_grammar;`, and they assume that when compiled they will be placed on the classpath so that they don't need to explicitly import each other -- they're all in the same package. To this end, they assume you're running the compiler from the root of your project. Or, you can run the compiler from your main project classpath directory if it's not the root, and get files that will have working package names.

The point being, the compiler currently makes some assumptions about load path concerns -- it does something reasonable that doesn't require any input from the user. This could come up in other languages we already support, or ones we add later. So, anything that changes the output location should probably need to notify the compiler so it generates code that will work from there. Assuming the compiler is running from the source root of the project is a reasonable thing that reduces input required from the user and makes the compiler less complicated.

**Comment by atownley** [comment]
Hi James,

Yeah, I hadn’t looked at how it impacted the Java side of things.  However, normally when you’re doing code generation with Java, you give the output package name, and the generator writes files according to the directory structure provided.

I’ll have to have a closer look at how this actually works in Canopy.  It might actually be worth a separate java-specific argument, and ignoring the output argument completely.

Ideally, things like this would live only in the driver scripts, but the Java builder script is likely more complex.

I’ll think about it and look closer into it later.

It’s hard for me to really test things since I can’t reliably build, however.  Any ideas about that?

Cheers,

ast

> On Jul 18, 2017, at 8:22 PM, James Coglan <notifications@github.com> wrote:
> 
> Hi @atownley, this is a good idea. The only problem with the implementation is that it doesn't handle languages for which the compiler emits multiple files. For example, try running it with --lang java to see what I mean: only a single file is written, and it contains the contents of the last file the compiler emits, so all other compiler output is lost.
> 
> For multi-file outputs, we generate a directory named after the grammar; maybe --out should override that rather than supplying a literal filename. I'm not sure whether this could live in the bin script or whether the path would need to be passed into the builder/compiler, I'll leave that for you to decide.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Andrew S. Townley <ast@atownley.org>
http://atownley.org

**Comment by atownley** [comment]
Hi James,

It really depends on how you want the architecture to be.  Technically, using Java’s nested classes, you could avoid all of the complexity you describe (and the output file problem) completely.

I don’t think anything besides the external parser needs to be public, and the model used by Javascript of only exporting one interface could be used as well.

Based on the behavior you describe, I’m not sure having quite so many baked-in assumptions is a good idea.  I would see canopy’s job as being pretty straightforward:  take an input grammar (which can be anywhere) and then generate the language-specific files in the location and with the options of the user’s choosing.  Different languages would potentially require supporting different options.

It’s early, and I’m not quite awake yet, but I’d assumed that the Java output was a single java file.  I don’t see any reason that it shouldn’t be, and that it has a single public API.  Nested dependencies aren’t a problem, and the package definition should be specified as an argument on the command line for the generator.

I’ve written a lot of Java code since JDK 1.1 was released in 1997, and depending on your build tools, there’s a bunch of different ways you can structure your source.  The most common is nested directories, but that’s not required.

A —package-name argument allowing you to specify the package of the generated parser is the best bet, meaning that only one item needs to be defined within the generated source file, and the rest of the parser internals should be implemented as nested Java classes inside the public Parser API.

In lieu of the —package-name language-specific argument, parsing the path of the —output flag would be a reasonable default.  The main thing is that you have the ability to specify the generated parser’s package name (and potentially the class name) on the command line for Java without requiring post-processing and moving files around with build tools to integrate the parser into whatever approach and structure you’re using.

For now, I’ve pulled back on using Canopy for any other language than javascript because I want to make sure I understand how to use it.  I should get back to multi-language usage over the next few months, and it’ll likely require Ruby and Java, so it’ll matter more to me then than it does now :)

Cheers,

ast

> On Jul 18, 2017, at 8:37 PM, James Coglan <notifications@github.com> wrote:
> 
> Something else occurs to me, prompted by Java but it will affect other language backends we could implement. For JS, Python and Ruby this currently isn't a problem since we emit a single file with no dependencies, but for Java we emit multiple files. In general, multi-file exports will need to import each other, and they might not be able to do this in a strictly relative sense.
> 
> For example, if you run ./bin/canopy lib/meta_grammar.peg --lang java in this repo, the resulting files begin with package lib.meta_grammar;, and they assume that when compiled they will be placed on the classpath so that they don't need to explicitly import each other -- they're all in the same package. To this end, they assume you're running the compiler from the root of your project. Or, you can run the compiler from your main project classpath directory if it's not the root, and get files that will have working package names.
> 
> The point being, the compiler currently makes some assumptions about load path concerns -- it does something reasonable that doesn't require any input from the user. This could come up in other languages we already support, or ones we add later. So, anything that changes the output location should probably need to notify the compiler so it generates code that will work from there. Assuming the compiler is running from the source root of the project is a reasonable thing that reduces input required from the user and makes the compiler less complicated.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

--
Andrew S. Townley <ast@atownley.org>
http://atownley.org

**Comment by jcoglan** [comment]
Re: your comments here and on another issue about not being able to build the project, I've just updated `CONTRIBUTING.md` and it should reflect how things work now. Please let me know if it doesn't work for you.

**Comment by jcoglan** [comment]
> I don’t think anything besides the external parser needs to be public, and the model used by Javascript of only exporting one interface could be used as well.

At least three things need to be public: the parser class, the `ParseError` class, and the `Actions` interface, so we do need multiple output files. (Unless we nest these things, which I'm not a huge fan of from a user experience point of view.)

Re: your other comments, it's not so much about baked-in assumptions as that I want the command-line tool to be as consistent as possible across languages, and it should do something sensible by default without needing to be configured. In this case, generating the package name based on the relative location of the parser from the current working directory seemed like a reasonable default, and you can easily get a different package name by running the compiler from a different directory.

In principle I'd be open to an `--output` option that referred to a directory, not a file, for all languages, since multi-file builders need to retain control of the names of the files they generate. A Java-specific option like `--java-package` could work too if it's really not workable to control the package name by changing your working directory.

**Comment by atownley** [comment]
Hi James,

Cool! Thank you!

Haven’t messed with my parser for ages, so I’ll have a play when I get a chance.

Have a great rest of the week!

**Pull request closed without merging**
